/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './features/~__root'
import { Route as PrivateRouteImport } from './features/~_private'
import { Route as IndexRouteImport } from './features/~index'
import { Route as LoginIndexRouteImport } from './features/~login/~index'
import { Route as PrivateSystemMonitoringIndexRouteImport } from './features/~_private/~system-monitoring/~index'
import { Route as PrivateStatisticalIndexRouteImport } from './features/~_private/~statistical/~index'
import { Route as PrivateScheduleIndexRouteImport } from './features/~_private/~schedule/~index'
import { Route as PrivateRegistrationHistoryIndexRouteImport } from './features/~_private/~registration-history/~index'
import { Route as PrivateRegisterSessionIndexRouteImport } from './features/~_private/~register-session/~index'
import { Route as PrivateProfileIndexRouteImport } from './features/~_private/~profile/~index'
import { Route as PrivateLibraryIndexRouteImport } from './features/~_private/~library/~index'
import { Route as PrivateDashboardIndexRouteImport } from './features/~_private/~dashboard/~index'
import { Route as PrivateCourseIndexRouteImport } from './features/~_private/~course/~index'
import { Route as PrivateStatisticalReportsIndexRouteImport } from './features/~_private/~statistical/~reports/~index'
import { Route as PrivateStatisticalOverviewIndexRouteImport } from './features/~_private/~statistical/~overview/~index'
import { Route as PrivateStatisticalIdIndexRouteImport } from './features/~_private/~statistical/~$id/~index'
import { Route as PrivateScheduleRequestIndexRouteImport } from './features/~_private/~schedule/~request/~index'
import { Route as PrivateScheduleHistoryIndexRouteImport } from './features/~_private/~schedule/~history/~index'
import { Route as PrivateScheduleIdIndexRouteImport } from './features/~_private/~schedule/~$id/~index'
import { Route as PrivateRegisterSessionOverviewIndexRouteImport } from './features/~_private/~register-session/~overview/~index'
import { Route as PrivateLibraryQueryIndexRouteImport } from './features/~_private/~library/~$query/~index'
import { Route as PrivateCourseIdIndexRouteImport } from './features/~_private/~course/~$id/~index'
import { Route as PrivateScheduleRequestNewIndexRouteImport } from './features/~_private/~schedule/~request/~new/~index'
import { Route as PrivateScheduleHistoryIdIndexRouteImport } from './features/~_private/~schedule/~history/~$id/~index'
import { Route as PrivateCourseIdSubmissionsIndexRouteImport } from './features/~_private/~course/~$id/~submissions/~index'
import { Route as PrivateCourseIdRatingIndexRouteImport } from './features/~_private/~course/~$id/~rating/~index'
import { Route as PrivateCourseIdMembersIndexRouteImport } from './features/~_private/~course/~$id/~members/~index'
import { Route as PrivateCourseIdNameIndexRouteImport } from './features/~_private/~course/~$id/~$name/~index'
import { Route as PrivateCourseIdRatingIdIndexRouteImport } from './features/~_private/~course/~$id/~rating/~$id/~$index'
import { Route as PrivateCourseIdNameStunameIndexRouteImport } from './features/~_private/~course/~$id/~$name/~$stuname/~index'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSystemMonitoringIndexRoute =
  PrivateSystemMonitoringIndexRouteImport.update({
    id: '/system-monitoring/',
    path: '/system-monitoring/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateStatisticalIndexRoute = PrivateStatisticalIndexRouteImport.update({
  id: '/statistical/',
  path: '/statistical/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateScheduleIndexRoute = PrivateScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateRegistrationHistoryIndexRoute =
  PrivateRegistrationHistoryIndexRouteImport.update({
    id: '/registration-history/',
    path: '/registration-history/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateRegisterSessionIndexRoute =
  PrivateRegisterSessionIndexRouteImport.update({
    id: '/register-session/',
    path: '/register-session/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateLibraryIndexRoute = PrivateLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardIndexRoute = PrivateDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCourseIndexRoute = PrivateCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateStatisticalReportsIndexRoute =
  PrivateStatisticalReportsIndexRouteImport.update({
    id: '/statistical/reports/',
    path: '/statistical/reports/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateStatisticalOverviewIndexRoute =
  PrivateStatisticalOverviewIndexRouteImport.update({
    id: '/statistical/overview/',
    path: '/statistical/overview/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateStatisticalIdIndexRoute =
  PrivateStatisticalIdIndexRouteImport.update({
    id: '/statistical/$id/',
    path: '/statistical/$id/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateScheduleRequestIndexRoute =
  PrivateScheduleRequestIndexRouteImport.update({
    id: '/schedule/request/',
    path: '/schedule/request/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateScheduleHistoryIndexRoute =
  PrivateScheduleHistoryIndexRouteImport.update({
    id: '/schedule/history/',
    path: '/schedule/history/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateScheduleIdIndexRoute = PrivateScheduleIdIndexRouteImport.update({
  id: '/schedule/$id/',
  path: '/schedule/$id/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateRegisterSessionOverviewIndexRoute =
  PrivateRegisterSessionOverviewIndexRouteImport.update({
    id: '/register-session/overview/',
    path: '/register-session/overview/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateLibraryQueryIndexRoute =
  PrivateLibraryQueryIndexRouteImport.update({
    id: '/library/$query/',
    path: '/library/$query/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdIndexRoute = PrivateCourseIdIndexRouteImport.update({
  id: '/course/$id/',
  path: '/course/$id/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateScheduleRequestNewIndexRoute =
  PrivateScheduleRequestNewIndexRouteImport.update({
    id: '/schedule/request/new/',
    path: '/schedule/request/new/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateScheduleHistoryIdIndexRoute =
  PrivateScheduleHistoryIdIndexRouteImport.update({
    id: '/schedule/history/$id/',
    path: '/schedule/history/$id/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdSubmissionsIndexRoute =
  PrivateCourseIdSubmissionsIndexRouteImport.update({
    id: '/course/$id/submissions/',
    path: '/course/$id/submissions/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdRatingIndexRoute =
  PrivateCourseIdRatingIndexRouteImport.update({
    id: '/course/$id/rating/',
    path: '/course/$id/rating/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdMembersIndexRoute =
  PrivateCourseIdMembersIndexRouteImport.update({
    id: '/course/$id/members/',
    path: '/course/$id/members/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdNameIndexRoute =
  PrivateCourseIdNameIndexRouteImport.update({
    id: '/course/$id/$name/',
    path: '/course/$id/$name/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdRatingIdIndexRoute =
  PrivateCourseIdRatingIdIndexRouteImport.update({
    id: '/course/$id/rating/$id/$index',
    path: '/course/$id/rating/$id/$index',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdNameStunameIndexRoute =
  PrivateCourseIdNameStunameIndexRouteImport.update({
    id: '/course/$id/$name/$stuname/',
    path: '/course/$id/$name/$stuname/',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/course': typeof PrivateCourseIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/library': typeof PrivateLibraryIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/register-session': typeof PrivateRegisterSessionIndexRoute
  '/registration-history': typeof PrivateRegistrationHistoryIndexRoute
  '/schedule': typeof PrivateScheduleIndexRoute
  '/statistical': typeof PrivateStatisticalIndexRoute
  '/system-monitoring': typeof PrivateSystemMonitoringIndexRoute
  '/course/$id': typeof PrivateCourseIdIndexRoute
  '/library/$query': typeof PrivateLibraryQueryIndexRoute
  '/register-session/overview': typeof PrivateRegisterSessionOverviewIndexRoute
  '/schedule/$id': typeof PrivateScheduleIdIndexRoute
  '/schedule/history': typeof PrivateScheduleHistoryIndexRoute
  '/schedule/request': typeof PrivateScheduleRequestIndexRoute
  '/statistical/$id': typeof PrivateStatisticalIdIndexRoute
  '/statistical/overview': typeof PrivateStatisticalOverviewIndexRoute
  '/statistical/reports': typeof PrivateStatisticalReportsIndexRoute
  '/course/$id/$name': typeof PrivateCourseIdNameIndexRoute
  '/course/$id/members': typeof PrivateCourseIdMembersIndexRoute
  '/course/$id/rating': typeof PrivateCourseIdRatingIndexRoute
  '/course/$id/submissions': typeof PrivateCourseIdSubmissionsIndexRoute
  '/schedule/history/$id': typeof PrivateScheduleHistoryIdIndexRoute
  '/schedule/request/new': typeof PrivateScheduleRequestNewIndexRoute
  '/course/$id/$name/$stuname': typeof PrivateCourseIdNameStunameIndexRoute
  '/course/$id/rating/$id/$index': typeof PrivateCourseIdRatingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/course': typeof PrivateCourseIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/library': typeof PrivateLibraryIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/register-session': typeof PrivateRegisterSessionIndexRoute
  '/registration-history': typeof PrivateRegistrationHistoryIndexRoute
  '/schedule': typeof PrivateScheduleIndexRoute
  '/statistical': typeof PrivateStatisticalIndexRoute
  '/system-monitoring': typeof PrivateSystemMonitoringIndexRoute
  '/course/$id': typeof PrivateCourseIdIndexRoute
  '/library/$query': typeof PrivateLibraryQueryIndexRoute
  '/register-session/overview': typeof PrivateRegisterSessionOverviewIndexRoute
  '/schedule/$id': typeof PrivateScheduleIdIndexRoute
  '/schedule/history': typeof PrivateScheduleHistoryIndexRoute
  '/schedule/request': typeof PrivateScheduleRequestIndexRoute
  '/statistical/$id': typeof PrivateStatisticalIdIndexRoute
  '/statistical/overview': typeof PrivateStatisticalOverviewIndexRoute
  '/statistical/reports': typeof PrivateStatisticalReportsIndexRoute
  '/course/$id/$name': typeof PrivateCourseIdNameIndexRoute
  '/course/$id/members': typeof PrivateCourseIdMembersIndexRoute
  '/course/$id/rating': typeof PrivateCourseIdRatingIndexRoute
  '/course/$id/submissions': typeof PrivateCourseIdSubmissionsIndexRoute
  '/schedule/history/$id': typeof PrivateScheduleHistoryIdIndexRoute
  '/schedule/request/new': typeof PrivateScheduleRequestNewIndexRoute
  '/course/$id/$name/$stuname': typeof PrivateCourseIdNameStunameIndexRoute
  '/course/$id/rating/$id/$index': typeof PrivateCourseIdRatingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_private/course/': typeof PrivateCourseIndexRoute
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/_private/library/': typeof PrivateLibraryIndexRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/_private/register-session/': typeof PrivateRegisterSessionIndexRoute
  '/_private/registration-history/': typeof PrivateRegistrationHistoryIndexRoute
  '/_private/schedule/': typeof PrivateScheduleIndexRoute
  '/_private/statistical/': typeof PrivateStatisticalIndexRoute
  '/_private/system-monitoring/': typeof PrivateSystemMonitoringIndexRoute
  '/_private/course/$id/': typeof PrivateCourseIdIndexRoute
  '/_private/library/$query/': typeof PrivateLibraryQueryIndexRoute
  '/_private/register-session/overview/': typeof PrivateRegisterSessionOverviewIndexRoute
  '/_private/schedule/$id/': typeof PrivateScheduleIdIndexRoute
  '/_private/schedule/history/': typeof PrivateScheduleHistoryIndexRoute
  '/_private/schedule/request/': typeof PrivateScheduleRequestIndexRoute
  '/_private/statistical/$id/': typeof PrivateStatisticalIdIndexRoute
  '/_private/statistical/overview/': typeof PrivateStatisticalOverviewIndexRoute
  '/_private/statistical/reports/': typeof PrivateStatisticalReportsIndexRoute
  '/_private/course/$id/$name/': typeof PrivateCourseIdNameIndexRoute
  '/_private/course/$id/members/': typeof PrivateCourseIdMembersIndexRoute
  '/_private/course/$id/rating/': typeof PrivateCourseIdRatingIndexRoute
  '/_private/course/$id/submissions/': typeof PrivateCourseIdSubmissionsIndexRoute
  '/_private/schedule/history/$id/': typeof PrivateScheduleHistoryIdIndexRoute
  '/_private/schedule/request/new/': typeof PrivateScheduleRequestNewIndexRoute
  '/_private/course/$id/$name/$stuname/': typeof PrivateCourseIdNameStunameIndexRoute
  '/_private/course/$id/rating/$id/$index': typeof PrivateCourseIdRatingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/course'
    | '/dashboard'
    | '/library'
    | '/profile'
    | '/register-session'
    | '/registration-history'
    | '/schedule'
    | '/statistical'
    | '/system-monitoring'
    | '/course/$id'
    | '/library/$query'
    | '/register-session/overview'
    | '/schedule/$id'
    | '/schedule/history'
    | '/schedule/request'
    | '/statistical/$id'
    | '/statistical/overview'
    | '/statistical/reports'
    | '/course/$id/$name'
    | '/course/$id/members'
    | '/course/$id/rating'
    | '/course/$id/submissions'
    | '/schedule/history/$id'
    | '/schedule/request/new'
    | '/course/$id/$name/$stuname'
    | '/course/$id/rating/$id/$index'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/course'
    | '/dashboard'
    | '/library'
    | '/profile'
    | '/register-session'
    | '/registration-history'
    | '/schedule'
    | '/statistical'
    | '/system-monitoring'
    | '/course/$id'
    | '/library/$query'
    | '/register-session/overview'
    | '/schedule/$id'
    | '/schedule/history'
    | '/schedule/request'
    | '/statistical/$id'
    | '/statistical/overview'
    | '/statistical/reports'
    | '/course/$id/$name'
    | '/course/$id/members'
    | '/course/$id/rating'
    | '/course/$id/submissions'
    | '/schedule/history/$id'
    | '/schedule/request/new'
    | '/course/$id/$name/$stuname'
    | '/course/$id/rating/$id/$index'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login/'
    | '/_private/course/'
    | '/_private/dashboard/'
    | '/_private/library/'
    | '/_private/profile/'
    | '/_private/register-session/'
    | '/_private/registration-history/'
    | '/_private/schedule/'
    | '/_private/statistical/'
    | '/_private/system-monitoring/'
    | '/_private/course/$id/'
    | '/_private/library/$query/'
    | '/_private/register-session/overview/'
    | '/_private/schedule/$id/'
    | '/_private/schedule/history/'
    | '/_private/schedule/request/'
    | '/_private/statistical/$id/'
    | '/_private/statistical/overview/'
    | '/_private/statistical/reports/'
    | '/_private/course/$id/$name/'
    | '/_private/course/$id/members/'
    | '/_private/course/$id/rating/'
    | '/_private/course/$id/submissions/'
    | '/_private/schedule/history/$id/'
    | '/_private/schedule/request/new/'
    | '/_private/course/$id/$name/$stuname/'
    | '/_private/course/$id/rating/$id/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/system-monitoring/': {
      id: '/_private/system-monitoring/'
      path: '/system-monitoring'
      fullPath: '/system-monitoring'
      preLoaderRoute: typeof PrivateSystemMonitoringIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/statistical/': {
      id: '/_private/statistical/'
      path: '/statistical'
      fullPath: '/statistical'
      preLoaderRoute: typeof PrivateStatisticalIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/schedule/': {
      id: '/_private/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof PrivateScheduleIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/registration-history/': {
      id: '/_private/registration-history/'
      path: '/registration-history'
      fullPath: '/registration-history'
      preLoaderRoute: typeof PrivateRegistrationHistoryIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/register-session/': {
      id: '/_private/register-session/'
      path: '/register-session'
      fullPath: '/register-session'
      preLoaderRoute: typeof PrivateRegisterSessionIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/library/': {
      id: '/_private/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof PrivateLibraryIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/': {
      id: '/_private/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof PrivateCourseIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/statistical/reports/': {
      id: '/_private/statistical/reports/'
      path: '/statistical/reports'
      fullPath: '/statistical/reports'
      preLoaderRoute: typeof PrivateStatisticalReportsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/statistical/overview/': {
      id: '/_private/statistical/overview/'
      path: '/statistical/overview'
      fullPath: '/statistical/overview'
      preLoaderRoute: typeof PrivateStatisticalOverviewIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/statistical/$id/': {
      id: '/_private/statistical/$id/'
      path: '/statistical/$id'
      fullPath: '/statistical/$id'
      preLoaderRoute: typeof PrivateStatisticalIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/schedule/request/': {
      id: '/_private/schedule/request/'
      path: '/schedule/request'
      fullPath: '/schedule/request'
      preLoaderRoute: typeof PrivateScheduleRequestIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/schedule/history/': {
      id: '/_private/schedule/history/'
      path: '/schedule/history'
      fullPath: '/schedule/history'
      preLoaderRoute: typeof PrivateScheduleHistoryIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/schedule/$id/': {
      id: '/_private/schedule/$id/'
      path: '/schedule/$id'
      fullPath: '/schedule/$id'
      preLoaderRoute: typeof PrivateScheduleIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/register-session/overview/': {
      id: '/_private/register-session/overview/'
      path: '/register-session/overview'
      fullPath: '/register-session/overview'
      preLoaderRoute: typeof PrivateRegisterSessionOverviewIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/library/$query/': {
      id: '/_private/library/$query/'
      path: '/library/$query'
      fullPath: '/library/$query'
      preLoaderRoute: typeof PrivateLibraryQueryIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/': {
      id: '/_private/course/$id/'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof PrivateCourseIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/schedule/request/new/': {
      id: '/_private/schedule/request/new/'
      path: '/schedule/request/new'
      fullPath: '/schedule/request/new'
      preLoaderRoute: typeof PrivateScheduleRequestNewIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/schedule/history/$id/': {
      id: '/_private/schedule/history/$id/'
      path: '/schedule/history/$id'
      fullPath: '/schedule/history/$id'
      preLoaderRoute: typeof PrivateScheduleHistoryIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/submissions/': {
      id: '/_private/course/$id/submissions/'
      path: '/course/$id/submissions'
      fullPath: '/course/$id/submissions'
      preLoaderRoute: typeof PrivateCourseIdSubmissionsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/rating/': {
      id: '/_private/course/$id/rating/'
      path: '/course/$id/rating'
      fullPath: '/course/$id/rating'
      preLoaderRoute: typeof PrivateCourseIdRatingIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/members/': {
      id: '/_private/course/$id/members/'
      path: '/course/$id/members'
      fullPath: '/course/$id/members'
      preLoaderRoute: typeof PrivateCourseIdMembersIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/$name/': {
      id: '/_private/course/$id/$name/'
      path: '/course/$id/$name'
      fullPath: '/course/$id/$name'
      preLoaderRoute: typeof PrivateCourseIdNameIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/rating/$id/$index': {
      id: '/_private/course/$id/rating/$id/$index'
      path: '/course/$id/rating/$id/$index'
      fullPath: '/course/$id/rating/$id/$index'
      preLoaderRoute: typeof PrivateCourseIdRatingIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/$name/$stuname/': {
      id: '/_private/course/$id/$name/$stuname/'
      path: '/course/$id/$name/$stuname'
      fullPath: '/course/$id/$name/$stuname'
      preLoaderRoute: typeof PrivateCourseIdNameStunameIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateCourseIndexRoute: typeof PrivateCourseIndexRoute
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
  PrivateLibraryIndexRoute: typeof PrivateLibraryIndexRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
  PrivateRegisterSessionIndexRoute: typeof PrivateRegisterSessionIndexRoute
  PrivateRegistrationHistoryIndexRoute: typeof PrivateRegistrationHistoryIndexRoute
  PrivateScheduleIndexRoute: typeof PrivateScheduleIndexRoute
  PrivateStatisticalIndexRoute: typeof PrivateStatisticalIndexRoute
  PrivateSystemMonitoringIndexRoute: typeof PrivateSystemMonitoringIndexRoute
  PrivateCourseIdIndexRoute: typeof PrivateCourseIdIndexRoute
  PrivateLibraryQueryIndexRoute: typeof PrivateLibraryQueryIndexRoute
  PrivateRegisterSessionOverviewIndexRoute: typeof PrivateRegisterSessionOverviewIndexRoute
  PrivateScheduleIdIndexRoute: typeof PrivateScheduleIdIndexRoute
  PrivateScheduleHistoryIndexRoute: typeof PrivateScheduleHistoryIndexRoute
  PrivateScheduleRequestIndexRoute: typeof PrivateScheduleRequestIndexRoute
  PrivateStatisticalIdIndexRoute: typeof PrivateStatisticalIdIndexRoute
  PrivateStatisticalOverviewIndexRoute: typeof PrivateStatisticalOverviewIndexRoute
  PrivateStatisticalReportsIndexRoute: typeof PrivateStatisticalReportsIndexRoute
  PrivateCourseIdNameIndexRoute: typeof PrivateCourseIdNameIndexRoute
  PrivateCourseIdMembersIndexRoute: typeof PrivateCourseIdMembersIndexRoute
  PrivateCourseIdRatingIndexRoute: typeof PrivateCourseIdRatingIndexRoute
  PrivateCourseIdSubmissionsIndexRoute: typeof PrivateCourseIdSubmissionsIndexRoute
  PrivateScheduleHistoryIdIndexRoute: typeof PrivateScheduleHistoryIdIndexRoute
  PrivateScheduleRequestNewIndexRoute: typeof PrivateScheduleRequestNewIndexRoute
  PrivateCourseIdNameStunameIndexRoute: typeof PrivateCourseIdNameStunameIndexRoute
  PrivateCourseIdRatingIdIndexRoute: typeof PrivateCourseIdRatingIdIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateCourseIndexRoute: PrivateCourseIndexRoute,
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
  PrivateLibraryIndexRoute: PrivateLibraryIndexRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
  PrivateRegisterSessionIndexRoute: PrivateRegisterSessionIndexRoute,
  PrivateRegistrationHistoryIndexRoute: PrivateRegistrationHistoryIndexRoute,
  PrivateScheduleIndexRoute: PrivateScheduleIndexRoute,
  PrivateStatisticalIndexRoute: PrivateStatisticalIndexRoute,
  PrivateSystemMonitoringIndexRoute: PrivateSystemMonitoringIndexRoute,
  PrivateCourseIdIndexRoute: PrivateCourseIdIndexRoute,
  PrivateLibraryQueryIndexRoute: PrivateLibraryQueryIndexRoute,
  PrivateRegisterSessionOverviewIndexRoute:
    PrivateRegisterSessionOverviewIndexRoute,
  PrivateScheduleIdIndexRoute: PrivateScheduleIdIndexRoute,
  PrivateScheduleHistoryIndexRoute: PrivateScheduleHistoryIndexRoute,
  PrivateScheduleRequestIndexRoute: PrivateScheduleRequestIndexRoute,
  PrivateStatisticalIdIndexRoute: PrivateStatisticalIdIndexRoute,
  PrivateStatisticalOverviewIndexRoute: PrivateStatisticalOverviewIndexRoute,
  PrivateStatisticalReportsIndexRoute: PrivateStatisticalReportsIndexRoute,
  PrivateCourseIdNameIndexRoute: PrivateCourseIdNameIndexRoute,
  PrivateCourseIdMembersIndexRoute: PrivateCourseIdMembersIndexRoute,
  PrivateCourseIdRatingIndexRoute: PrivateCourseIdRatingIndexRoute,
  PrivateCourseIdSubmissionsIndexRoute: PrivateCourseIdSubmissionsIndexRoute,
  PrivateScheduleHistoryIdIndexRoute: PrivateScheduleHistoryIdIndexRoute,
  PrivateScheduleRequestNewIndexRoute: PrivateScheduleRequestNewIndexRoute,
  PrivateCourseIdNameStunameIndexRoute: PrivateCourseIdNameStunameIndexRoute,
  PrivateCourseIdRatingIdIndexRoute: PrivateCourseIdRatingIdIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
