/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './features/~__root'
import { Route as PrivateRouteImport } from './features/~_private'
import { Route as IndexRouteImport } from './features/~index'
import { Route as SystemMonitoringIndexRouteImport } from './features/~system-monitoring/~index'
import { Route as StatisticalIndexRouteImport } from './features/~statistical/~index'
import { Route as ScheduleIndexRouteImport } from './features/~schedule/~index'
import { Route as RegistrationHistoryIndexRouteImport } from './features/~registration-history/~index'
import { Route as RegisterSessionIndexRouteImport } from './features/~register-session/~index'
import { Route as LoginIndexRouteImport } from './features/~login/~index'
import { Route as LibraryIndexRouteImport } from './features/~library/~index'
import { Route as StatisticalReportsIndexRouteImport } from './features/~statistical/~reports/~index'
import { Route as StatisticalOverviewIndexRouteImport } from './features/~statistical/~overview/~index'
import { Route as LibraryQueryIndexRouteImport } from './features/~library/~$query/~index'
import { Route as PrivateProfileIndexRouteImport } from './features/~_private/~profile/~index'
import { Route as PrivateDashboardIndexRouteImport } from './features/~_private/~dashboard/~index'
import { Route as PrivateCourseIndexRouteImport } from './features/~_private/~course/~index'
import { Route as PrivateCourseIdIndexRouteImport } from './features/~_private/~course/~$id/~index'
import { Route as PrivateCourseIdSubmissionsIndexRouteImport } from './features/~_private/~course/~$id/~submissions/~index'
import { Route as PrivateCourseIdMembersIndexRouteImport } from './features/~_private/~course/~$id/~members/~index'
import { Route as PrivateCourseIdNameIndexRouteImport } from './features/~_private/~course/~$id/~$name/~index'
import { Route as PrivateCourseIdNameStunameIndexRouteImport } from './features/~_private/~course/~$id/~$name/~$stuname/~index'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMonitoringIndexRoute = SystemMonitoringIndexRouteImport.update({
  id: '/system-monitoring/',
  path: '/system-monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticalIndexRoute = StatisticalIndexRouteImport.update({
  id: '/statistical/',
  path: '/statistical/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationHistoryIndexRoute =
  RegistrationHistoryIndexRouteImport.update({
    id: '/registration-history/',
    path: '/registration-history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterSessionIndexRoute = RegisterSessionIndexRouteImport.update({
  id: '/register-session/',
  path: '/register-session/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticalReportsIndexRoute = StatisticalReportsIndexRouteImport.update({
  id: '/statistical/reports/',
  path: '/statistical/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticalOverviewIndexRoute =
  StatisticalOverviewIndexRouteImport.update({
    id: '/statistical/overview/',
    path: '/statistical/overview/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryQueryIndexRoute = LibraryQueryIndexRouteImport.update({
  id: '/library/$query/',
  path: '/library/$query/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardIndexRoute = PrivateDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCourseIndexRoute = PrivateCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCourseIdIndexRoute = PrivateCourseIdIndexRouteImport.update({
  id: '/course/$id/',
  path: '/course/$id/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCourseIdSubmissionsIndexRoute =
  PrivateCourseIdSubmissionsIndexRouteImport.update({
    id: '/course/$id/submissions/',
    path: '/course/$id/submissions/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdMembersIndexRoute =
  PrivateCourseIdMembersIndexRouteImport.update({
    id: '/course/$id/members/',
    path: '/course/$id/members/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdNameIndexRoute =
  PrivateCourseIdNameIndexRouteImport.update({
    id: '/course/$id/$name/',
    path: '/course/$id/$name/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateCourseIdNameStunameIndexRoute =
  PrivateCourseIdNameStunameIndexRouteImport.update({
    id: '/course/$id/$name/$stuname/',
    path: '/course/$id/$name/$stuname/',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryIndexRoute
  '/login': typeof LoginIndexRoute
  '/register-session': typeof RegisterSessionIndexRoute
  '/registration-history': typeof RegistrationHistoryIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/statistical': typeof StatisticalIndexRoute
  '/system-monitoring': typeof SystemMonitoringIndexRoute
  '/course': typeof PrivateCourseIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/library/$query': typeof LibraryQueryIndexRoute
  '/statistical/overview': typeof StatisticalOverviewIndexRoute
  '/statistical/reports': typeof StatisticalReportsIndexRoute
  '/course/$id': typeof PrivateCourseIdIndexRoute
  '/course/$id/$name': typeof PrivateCourseIdNameIndexRoute
  '/course/$id/members': typeof PrivateCourseIdMembersIndexRoute
  '/course/$id/submissions': typeof PrivateCourseIdSubmissionsIndexRoute
  '/course/$id/$name/$stuname': typeof PrivateCourseIdNameStunameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryIndexRoute
  '/login': typeof LoginIndexRoute
  '/register-session': typeof RegisterSessionIndexRoute
  '/registration-history': typeof RegistrationHistoryIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/statistical': typeof StatisticalIndexRoute
  '/system-monitoring': typeof SystemMonitoringIndexRoute
  '/course': typeof PrivateCourseIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/library/$query': typeof LibraryQueryIndexRoute
  '/statistical/overview': typeof StatisticalOverviewIndexRoute
  '/statistical/reports': typeof StatisticalReportsIndexRoute
  '/course/$id': typeof PrivateCourseIdIndexRoute
  '/course/$id/$name': typeof PrivateCourseIdNameIndexRoute
  '/course/$id/members': typeof PrivateCourseIdMembersIndexRoute
  '/course/$id/submissions': typeof PrivateCourseIdSubmissionsIndexRoute
  '/course/$id/$name/$stuname': typeof PrivateCourseIdNameStunameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/library/': typeof LibraryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register-session/': typeof RegisterSessionIndexRoute
  '/registration-history/': typeof RegistrationHistoryIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/statistical/': typeof StatisticalIndexRoute
  '/system-monitoring/': typeof SystemMonitoringIndexRoute
  '/_private/course/': typeof PrivateCourseIndexRoute
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/library/$query/': typeof LibraryQueryIndexRoute
  '/statistical/overview/': typeof StatisticalOverviewIndexRoute
  '/statistical/reports/': typeof StatisticalReportsIndexRoute
  '/_private/course/$id/': typeof PrivateCourseIdIndexRoute
  '/_private/course/$id/$name/': typeof PrivateCourseIdNameIndexRoute
  '/_private/course/$id/members/': typeof PrivateCourseIdMembersIndexRoute
  '/_private/course/$id/submissions/': typeof PrivateCourseIdSubmissionsIndexRoute
  '/_private/course/$id/$name/$stuname/': typeof PrivateCourseIdNameStunameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/register-session'
    | '/registration-history'
    | '/schedule'
    | '/statistical'
    | '/system-monitoring'
    | '/course'
    | '/dashboard'
    | '/profile'
    | '/library/$query'
    | '/statistical/overview'
    | '/statistical/reports'
    | '/course/$id'
    | '/course/$id/$name'
    | '/course/$id/members'
    | '/course/$id/submissions'
    | '/course/$id/$name/$stuname'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/register-session'
    | '/registration-history'
    | '/schedule'
    | '/statistical'
    | '/system-monitoring'
    | '/course'
    | '/dashboard'
    | '/profile'
    | '/library/$query'
    | '/statistical/overview'
    | '/statistical/reports'
    | '/course/$id'
    | '/course/$id/$name'
    | '/course/$id/members'
    | '/course/$id/submissions'
    | '/course/$id/$name/$stuname'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/library/'
    | '/login/'
    | '/register-session/'
    | '/registration-history/'
    | '/schedule/'
    | '/statistical/'
    | '/system-monitoring/'
    | '/_private/course/'
    | '/_private/dashboard/'
    | '/_private/profile/'
    | '/library/$query/'
    | '/statistical/overview/'
    | '/statistical/reports/'
    | '/_private/course/$id/'
    | '/_private/course/$id/$name/'
    | '/_private/course/$id/members/'
    | '/_private/course/$id/submissions/'
    | '/_private/course/$id/$name/$stuname/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LibraryIndexRoute: typeof LibraryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterSessionIndexRoute: typeof RegisterSessionIndexRoute
  RegistrationHistoryIndexRoute: typeof RegistrationHistoryIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  StatisticalIndexRoute: typeof StatisticalIndexRoute
  SystemMonitoringIndexRoute: typeof SystemMonitoringIndexRoute
  LibraryQueryIndexRoute: typeof LibraryQueryIndexRoute
  StatisticalOverviewIndexRoute: typeof StatisticalOverviewIndexRoute
  StatisticalReportsIndexRoute: typeof StatisticalReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-monitoring/': {
      id: '/system-monitoring/'
      path: '/system-monitoring'
      fullPath: '/system-monitoring'
      preLoaderRoute: typeof SystemMonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistical/': {
      id: '/statistical/'
      path: '/statistical'
      fullPath: '/statistical'
      preLoaderRoute: typeof StatisticalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-history/': {
      id: '/registration-history/'
      path: '/registration-history'
      fullPath: '/registration-history'
      preLoaderRoute: typeof RegistrationHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-session/': {
      id: '/register-session/'
      path: '/register-session'
      fullPath: '/register-session'
      preLoaderRoute: typeof RegisterSessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistical/reports/': {
      id: '/statistical/reports/'
      path: '/statistical/reports'
      fullPath: '/statistical/reports'
      preLoaderRoute: typeof StatisticalReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistical/overview/': {
      id: '/statistical/overview/'
      path: '/statistical/overview'
      fullPath: '/statistical/overview'
      preLoaderRoute: typeof StatisticalOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$query/': {
      id: '/library/$query/'
      path: '/library/$query'
      fullPath: '/library/$query'
      preLoaderRoute: typeof LibraryQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/': {
      id: '/_private/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof PrivateCourseIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/': {
      id: '/_private/course/$id/'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof PrivateCourseIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/submissions/': {
      id: '/_private/course/$id/submissions/'
      path: '/course/$id/submissions'
      fullPath: '/course/$id/submissions'
      preLoaderRoute: typeof PrivateCourseIdSubmissionsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/members/': {
      id: '/_private/course/$id/members/'
      path: '/course/$id/members'
      fullPath: '/course/$id/members'
      preLoaderRoute: typeof PrivateCourseIdMembersIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/$name/': {
      id: '/_private/course/$id/$name/'
      path: '/course/$id/$name'
      fullPath: '/course/$id/$name'
      preLoaderRoute: typeof PrivateCourseIdNameIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/course/$id/$name/$stuname/': {
      id: '/_private/course/$id/$name/$stuname/'
      path: '/course/$id/$name/$stuname'
      fullPath: '/course/$id/$name/$stuname'
      preLoaderRoute: typeof PrivateCourseIdNameStunameIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateCourseIndexRoute: typeof PrivateCourseIndexRoute
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
  PrivateCourseIdIndexRoute: typeof PrivateCourseIdIndexRoute
  PrivateCourseIdNameIndexRoute: typeof PrivateCourseIdNameIndexRoute
  PrivateCourseIdMembersIndexRoute: typeof PrivateCourseIdMembersIndexRoute
  PrivateCourseIdSubmissionsIndexRoute: typeof PrivateCourseIdSubmissionsIndexRoute
  PrivateCourseIdNameStunameIndexRoute: typeof PrivateCourseIdNameStunameIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateCourseIndexRoute: PrivateCourseIndexRoute,
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
  PrivateCourseIdIndexRoute: PrivateCourseIdIndexRoute,
  PrivateCourseIdNameIndexRoute: PrivateCourseIdNameIndexRoute,
  PrivateCourseIdMembersIndexRoute: PrivateCourseIdMembersIndexRoute,
  PrivateCourseIdSubmissionsIndexRoute: PrivateCourseIdSubmissionsIndexRoute,
  PrivateCourseIdNameStunameIndexRoute: PrivateCourseIdNameStunameIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LibraryIndexRoute: LibraryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterSessionIndexRoute: RegisterSessionIndexRoute,
  RegistrationHistoryIndexRoute: RegistrationHistoryIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  StatisticalIndexRoute: StatisticalIndexRoute,
  SystemMonitoringIndexRoute: SystemMonitoringIndexRoute,
  LibraryQueryIndexRoute: LibraryQueryIndexRoute,
  StatisticalOverviewIndexRoute: StatisticalOverviewIndexRoute,
  StatisticalReportsIndexRoute: StatisticalReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
